apiVersion: v1
kind: Service
metadata:
  name: my-web-app-service
spec:
  type: LoadBalancer # 외부에서 접속할 수 있는 타입입니다.
  selector:
    app: my-web-app # deployment.yaml에서 정한 라벨과 같아야 합니다.
  ports:
    - protocol: TCP
      port: 80 # 외부로 노출할 포트 (브라우저 접속용)
      targetPort: 3000 # 컨테이너가 사용 중인 실제 포트